// Dict of Letters (key is letter, val is used for toggling them)
export const alphabet = {
    'Q': false,
    'W': false,
    'E': false,
    'R': false,
    'T': false,
    'Y': false,
    'U': false,
    'I': false,
    'O': false,
    'P': false,
    'A': false,
    'S': false,
    'D': false,
    'F': false,
    'G': false,
    'H': false,
    'J': false,
    'K': false,
    'L': false,
    'Z': false,
    'X': false,
    'C': false,
    'V': false,
    'B': false,
    'N': false,
    'M': false,
}